<?php

namespace Badgio\FeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedCacheRepository extends EntityRepository
{
}
