<?php

namespace Badgio\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Category_FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Category_FeedRepository extends EntityRepository
{
}
